{
    "openapi": "3.0.1",
    "info": {
        "title": "LanguageTool API",
        "description": "Check texts for style and grammar issues with LanguageTool. See <a\nhref='http://wiki.languagetool.org/public-http-api'>our wiki</a> for access limitations.",
        "version": "1.0.2"
    },
    "servers": [
        {
            "url": "http://localhost:9003/v2"
        }
    ],
    "paths": {
        "/check": {
            "post": {
                "summary": "Check a text",
                "description": "The main feature - check a text with LanguageTool for possible\nstyle and grammar issues.",
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "required": [
                                    "language"
                                ],
                                "properties": {
                                    "text": {
                                        "type": "string",
                                        "description": "The text to be checked. This or 'data' is required."
                                    },
                                    "data": {
                                        "type": "string",
                                        "description": "The text to be checked, given as a JSON document that specifies what's text and what's markup. This or 'text' is required. Markup will be ignored when looking for errors. Example text: <pre>A &lt;b>test&lt;/b></pre>JSON for the example text: <pre>{\"annotation\":[\n {\"text\": \"A \"},\n {\"markup\": \"&lt;b>\"},\n {\"text\": \"test\"},\n {\"markup\": \"&lt;/b>\"}\n]}</pre> <p>If you have markup that should be interpreted as whitespace, like <tt>&lt;p&gt;</tt> in HTML, you can have it interpreted like this: <pre>{\"markup\": \"&lt;p&gt;\", \"interpretAs\": \"\\n\\n\"}</pre><p>The 'data' feature is not limited to HTML or XML, it can be used for any kind of markup."
                                    },
                                    "language": {
                                        "type": "string",
                                        "description": "A language code like `en-US`, `de-DE`, `fr`, or `auto`\nto guess the language automatically (see `preferredVariants` below).\nFor languages with variants (English, German, Portuguese) spell\nchecking will only be activated when you specify the variant,\ne.g. `en-GB` instead of just `en`.",
                                        "minLength": 2,
                                        "maxLength": 5
                                    },
                                    "altLanguages": {
                                        "type": "string",
                                        "description": "EXPERIMENTAL: Comma-separated list of language codes\nto check if a word is not similar to one of the main language\n(parameter `language`). Unknown words that are similar to a word\nfrom the main language will still be considered errors but with\ntype `Hint`. For languages with variants (English, German, Portuguese)\nyou need to specify the variant, e.g. `en-GB` instead of just\n`en`.",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "motherTongue": {
                                        "type": "string",
                                        "description": "A language code of the user's native language, enabling\nfalse friends checks for some language pairs.",
                                        "minLength": 2,
                                        "maxLength": 3
                                    },
                                    "preferredVariants": {
                                        "type": "string",
                                        "description": "Comma-separated list of preferred language variants.\nThe language detector used with `language=auto` can detect e.g.\nEnglish, but it cannot decide whether British English or American\nEnglish is used. Thus this parameter can be used to specify the\npreferred variants like `en-GB` and `de-AT`. Only available with\n`language=auto`.",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "enabledRules": {
                                        "type": "string",
                                        "description": "IDs of rules to be enabled, comma-separated",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "disabledRules": {
                                        "type": "string",
                                        "description": "IDs of rules to be disabled, comma-separated",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "enabledCategories": {
                                        "type": "string",
                                        "description": "IDs of categories to be enabled, comma-separated",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "disabledCategories": {
                                        "type": "string",
                                        "description": "IDs of categories to be disabled, comma-separated",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "enabledOnly": {
                                        "type": "boolean",
                                        "description": "If true, only the rules and categories whose IDs are\nspecified with `enabledRules` or `enabledCategories` are enabled.",
                                        "default": false
                                    }
                                },
                                "x-dependencies": [
                                    "Or(text, data)",
                                    "Or(data, text);"
                                ]
                            },
                            "examples": {
                                "example0": {
                                    "value": {
                                        "data": "<pre>A &lt;b>test&lt;/b></pre>",
                                        "language": "en-US",
                                        "altLanguages": "en-US",
                                        "motherTongue": "en",
                                        "preferredVariants": "en-GB",
                                        "enabledOnly": "True"
                                    }
                                },
                                "example1": {
                                    "value": {
                                        "data": "<pre>{\"annotation\":[\n {\"text\": \"A \"},\n {\"markup\": \"&lt;b>\"},\n {\"text\": \"test\"},\n {\"markup\": \"&lt;/b>\"}\n]}</pre>",
                                        "language": "de-DE",
                                        "altLanguages": "en-CA",
                                        "motherTongue": "fr",
                                        "preferredVariants": "de-AT",
                                        "enabledOnly": "False"
                                    }
                                },
                                "example2": {
                                    "value": {
                                        "data": "<pre>{\"markup\": \"&lt;p&gt;\"",
                                        "language": "fr",
                                        "altLanguages": "en-AU",
                                        "motherTongue": "de",
                                        "preferredVariants": "en-US"
                                    }
                                },
                                "example3": {
                                    "value": {
                                        "data": "\"interpretAs\": \"\\n\\n\"}</pre>",
                                        "language": "auto",
                                        "altLanguages": "en-NZ",
                                        "motherTongue": "es",
                                        "preferredVariants": "fr-FR"
                                    }
                                },
                                "example4": {
                                    "value": {
                                        "data": "<pre>&lt;div>Example text&lt;/div></pre>",
                                        "language": "en-GB",
                                        "altLanguages": "en-ZA",
                                        "motherTongue": "it",
                                        "preferredVariants": "es-ES"
                                    }
                                },
                                "example5": {
                                    "value": {
                                        "data": "<pre>{\"annotation\":[  {\"text\": \"Example \"}",
                                        "language": "en-AU",
                                        "altLanguages": "en-IN",
                                        "motherTongue": "pt",
                                        "preferredVariants": "it-IT"
                                    }
                                },
                                "example6": {
                                    "value": {
                                        "data": " {\"markup\": \"&lt;b>\"}",
                                        "language": "en-CA",
                                        "altLanguages": "en-GB",
                                        "motherTongue": "nl",
                                        "preferredVariants": "pt-BR"
                                    }
                                },
                                "example7": {
                                    "value": {
                                        "data": " {\"text\": \"text\"}",
                                        "language": "en-IN",
                                        "altLanguages": "de-DE",
                                        "motherTongue": "sv",
                                        "preferredVariants": "zh-CN"
                                    }
                                },
                                "example8": {
                                    "value": {
                                        "data": " {\"markup\": \"&lt;/b>\"} ]}</pre>",
                                        "language": "en-NZ",
                                        "altLanguages": "de-AT",
                                        "motherTongue": "da",
                                        "preferredVariants": "ja-JP"
                                    }
                                },
                                "example9": {
                                    "value": {
                                        "data": "<pre>{\"markup\": \"&lt;p&gt;\"",
                                        "language": "en-ZA",
                                        "altLanguages": "de-CH",
                                        "motherTongue": "no",
                                        "preferredVariants": "ko-KR"
                                    }
                                },
                                "example10": {
                                    "value": {
                                        "data": "\"interpretAs\": \"\\n\"}</pre>",
                                        "language": "de-AT",
                                        "altLanguages": "pt-BR",
                                        "motherTongue": "fi",
                                        "preferredVariants": "ru-RU"
                                    }
                                },
                                "example11": {
                                    "value": {
                                        "language": "de-CH",
                                        "altLanguages": "pt-PT",
                                        "motherTongue": "ru",
                                        "preferredVariants": "ar-SA"
                                    }
                                },
                                "example12": {
                                    "value": {
                                        "language": "de-LI",
                                        "altLanguages": "es-ES",
                                        "motherTongue": "pl",
                                        "preferredVariants": "hi-IN"
                                    }
                                },
                                "example13": {
                                    "value": {
                                        "language": "de-LU",
                                        "altLanguages": "es-MX",
                                        "motherTongue": "cs",
                                        "preferredVariants": "id-ID"
                                    }
                                },
                                "example14": {
                                    "value": {
                                        "language": "fr-BE",
                                        "altLanguages": "es-AR",
                                        "motherTongue": "hu",
                                        "preferredVariants": "tr-TR"
                                    }
                                },
                                "example15": {
                                    "value": {
                                        "language": "fr-CA",
                                        "altLanguages": "es-CO",
                                        "motherTongue": "ro",
                                        "preferredVariants": "nl-NL"
                                    }
                                },
                                "example16": {
                                    "value": {
                                        "language": "fr-CH",
                                        "altLanguages": "es-PE",
                                        "motherTongue": "bg",
                                        "preferredVariants": "pl-PL"
                                    }
                                },
                                "example17": {
                                    "value": {
                                        "language": "fr-LU",
                                        "altLanguages": "es-VE",
                                        "motherTongue": "el",
                                        "preferredVariants": "sv-SE"
                                    }
                                },
                                "example18": {
                                    "value": {
                                        "language": "fr-MC",
                                        "altLanguages": "es-CL",
                                        "motherTongue": "tr",
                                        "preferredVariants": "da-DK"
                                    }
                                },
                                "example19": {
                                    "value": {
                                        "language": "fr-MA",
                                        "altLanguages": "es-EC",
                                        "motherTongue": "ar",
                                        "preferredVariants": "fi-FI"
                                    }
                                },
                                "example20": {
                                    "value": {
                                        "language": "fr-DZ",
                                        "altLanguages": "es-DO",
                                        "motherTongue": "he",
                                        "preferredVariants": "nb-NO"
                                    }
                                },
                                "example21": {
                                    "value": {
                                        "language": "fr-TN",
                                        "altLanguages": "es-CR",
                                        "motherTongue": "ja",
                                        "preferredVariants": "el-GR"
                                    }
                                },
                                "example22": {
                                    "value": {
                                        "language": "fr-CI",
                                        "altLanguages": "es-PA",
                                        "motherTongue": "ko",
                                        "preferredVariants": "cs-CZ"
                                    }
                                },
                                "example23": {
                                    "value": {
                                        "language": "fr-SN",
                                        "altLanguages": "es-UY",
                                        "motherTongue": "zh",
                                        "preferredVariants": "hu-HU"
                                    }
                                },
                                "example24": {
                                    "value": {
                                        "language": "fr-CG",
                                        "altLanguages": "es-GT",
                                        "motherTongue": "th",
                                        "preferredVariants": "th-TH"
                                    }
                                },
                                "example25": {
                                    "value": {
                                        "language": "fr-CM",
                                        "altLanguages": "es-BO",
                                        "motherTongue": "vi",
                                        "preferredVariants": "he-IL"
                                    }
                                },
                                "example26": {
                                    "value": {
                                        "language": "fr-CD",
                                        "altLanguages": "es-HN",
                                        "preferredVariants": "vi-VN"
                                    }
                                },
                                "example27": {
                                    "value": {
                                        "language": "fr-GA",
                                        "altLanguages": "es-SV",
                                        "preferredVariants": "ro-RO"
                                    }
                                },
                                "example28": {
                                    "value": {
                                        "language": "fr-GF",
                                        "altLanguages": "es-NI",
                                        "preferredVariants": "uk-UA"
                                    }
                                },
                                "example29": {
                                    "value": {
                                        "language": "fr-GP",
                                        "altLanguages": "es-PR",
                                        "preferredVariants": "hr-HR"
                                    }
                                },
                                "example30": {
                                    "value": {
                                        "language": "fr-HT",
                                        "altLanguages": "es-PY",
                                        "preferredVariants": "bg-BG"
                                    }
                                },
                                "example31": {
                                    "value": {
                                        "language": "fr-MQ",
                                        "altLanguages": "es-US",
                                        "preferredVariants": "sr-RS"
                                    }
                                },
                                "example32": {
                                    "value": {
                                        "language": "fr-MR",
                                        "altLanguages": "es-CU",
                                        "preferredVariants": "sl-SI"
                                    }
                                },
                                "example33": {
                                    "value": {
                                        "language": "fr-MU",
                                        "preferredVariants": "sk-SK"
                                    }
                                },
                                "example34": {
                                    "value": {
                                        "language": "fr-NC",
                                        "preferredVariants": "lt-LT"
                                    }
                                },
                                "example35": {
                                    "value": {
                                        "language": "fr-PF",
                                        "preferredVariants": "lv-LV"
                                    }
                                },
                                "example36": {
                                    "value": {
                                        "language": "fr-RE",
                                        "preferredVariants": "et-EE"
                                    }
                                },
                                "example37": {
                                    "value": {
                                        "language": "fr-RW",
                                        "preferredVariants": "ms-MY"
                                    }
                                },
                                "example38": {
                                    "value": {
                                        "language": "fr-BL",
                                        "preferredVariants": "fa-IR"
                                    }
                                },
                                "example39": {
                                    "value": {
                                        "language": "fr-MF",
                                        "preferredVariants": "af-ZA"
                                    }
                                },
                                "example40": {
                                    "value": {
                                        "language": "fr-PM",
                                        "preferredVariants": "sq-AL"
                                    }
                                },
                                "example41": {
                                    "value": {
                                        "language": "fr-VC",
                                        "preferredVariants": "hy-AM"
                                    }
                                },
                                "example42": {
                                    "value": {
                                        "language": "fr-SC",
                                        "preferredVariants": "eu-ES"
                                    }
                                },
                                "example43": {
                                    "value": {
                                        "language": "fr-SY",
                                        "preferredVariants": "bn-BD"
                                    }
                                },
                                "example44": {
                                    "value": {
                                        "language": "fr-TG",
                                        "preferredVariants": "bs-BA"
                                    }
                                },
                                "example45": {
                                    "value": {
                                        "language": "fr-TD",
                                        "preferredVariants": "ca-ES"
                                    }
                                },
                                "example46": {
                                    "value": {
                                        "language": "fr",
                                        "preferredVariants": "cy-GB"
                                    }
                                },
                                "example47": {
                                    "value": {
                                        "preferredVariants": "eo-EO"
                                    }
                                },
                                "example48": {
                                    "value": {
                                        "preferredVariants": "fil-PH"
                                    }
                                },
                                "example49": {
                                    "value": {
                                        "preferredVariants": "ga-IE"
                                    }
                                },
                                "example50": {
                                    "value": {
                                        "preferredVariants": "gl-ES"
                                    }
                                },
                                "example51": {
                                    "value": {
                                        "preferredVariants": "gu-IN"
                                    }
                                },
                                "example52": {
                                    "value": {
                                        "preferredVariants": "ht-HT"
                                    }
                                },
                                "example53": {
                                    "value": {
                                        "preferredVariants": "is-IS"
                                    }
                                },
                                "example54": {
                                    "value": {
                                        "preferredVariants": "jv-ID"
                                    }
                                },
                                "example55": {
                                    "value": {
                                        "preferredVariants": "kn-IN"
                                    }
                                },
                                "example56": {
                                    "value": {
                                        "preferredVariants": "km-KH"
                                    }
                                },
                                "example57": {
                                    "value": {
                                        "preferredVariants": "ku-TR"
                                    }
                                },
                                "example58": {
                                    "value": {
                                        "preferredVariants": "ky-KG"
                                    }
                                },
                                "example59": {
                                    "value": {
                                        "preferredVariants": "lo-LA"
                                    }
                                },
                                "example60": {
                                    "value": {
                                        "preferredVariants": "mk-MK"
                                    }
                                },
                                "example61": {
                                    "value": {
                                        "preferredVariants": "ml-IN"
                                    }
                                },
                                "example62": {
                                    "value": {
                                        "preferredVariants": "mn-MN"
                                    }
                                },
                                "example63": {
                                    "value": {
                                        "preferredVariants": "mr-IN"
                                    }
                                },
                                "example64": {
                                    "value": {
                                        "preferredVariants": "ne-NP"
                                    }
                                },
                                "example65": {
                                    "value": {
                                        "preferredVariants": "pa-IN"
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "the result of checking the text",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/languages": {
            "get": {
                "summary": "Get a list of supported languages.",
                "responses": {
                    "200": {
                        "description": "An array of language objects.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "required": [
                                            "code",
                                            "longCode",
                                            "name"
                                        ],
                                        "type": "object",
                                        "properties": {
                                            "name": {
                                                "type": "string",
                                                "description": "a language name like 'French' or 'English (Australia)'"
                                            },
                                            "code": {
                                                "type": "string",
                                                "description": "a language code like 'en'"
                                            },
                                            "longCode": {
                                                "type": "string",
                                                "description": "a language code like 'en-US' or 'ca-ES-valencia'"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {}
}